name: Firmware Dumper

on:
  workflow_dispatch:
    inputs:
      link:
        description: 'Put Firmare Link'
        required: true

env:
  LINK: ${{ github.event.inputs.link }}
  ORG: AthenaPrjk
  TELEGRAM_CHAT: ${{ secrets.TELEGRAM_CHAT }}
  TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  TZ: Asia/Jakarta

jobs:
  dumper:
      runs-on: ubuntu-latest
      container:
            image: renayura/archlinux:latest

      steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Start dumping firmware
        run: |
             bash dumper.sh
